num = input('Digite um valor qualquer: ')
print(f'Valor digitado é {num}.')
print(f'O tipo do valor é {type(num)}')
print(f'[{num}] é numérico? R: {num.isnumeric()}')
print(f'[{num}] é alfabético? R: {num.isalpha()}')
print(f'[{num}] é apha-numérico? R: {num.isalnum()}')
print(f'[{num}] está em minúsculo? R: {num.islower()}')
print(f'[{num}] está em maiúsculo? R: {num.isupper()}')
print(f'[{num}] está capitalizada? R: {num.istitle()}')